### ISSUE TITLE
Demo-Seite

### ISSUE THREAD

**Issue by Monsterdog2k** [christianbarkowsky/contao-tabcontrol#34]
Hallo,

könnten auf der Demo-Seite die beiden CSS-Dateien für die Musterreiter veröffentlicht werden? Das würde beim Probieren einiges leichter machen.

Vielen Dank

**Comment by christianbarkowsky** [comment]
Wird erledigt!

**Comment by christianbarkowsky** [comment]
Hey @Monsterdog2k  ... hast dir das so?
https://brkwsky.de/tabcontrol-contao
