### ISSUE TITLE
Reiter-Element in Contao 4.8 im Debug-Modus nicht auswählbar

### ISSUE THREAD

**Issue by seibtph** [christianbarkowsky/contao-tabcontrol#38]
In Contao 4.8.0 erscheint das Reiter-Element leider nicht bei den Text-Elementen. Normalerweise sollte es ja unter dem Element "Markdown" stehen.

**Comment by seibtph** [comment]
Ich habe gerade bemerkt, dass das nur im neuen Debug-Modus, den man ja jetzt im Backend ein- und ausschalten kann, auftritt. Wenn der Debug-Modus aus ist wird das Element auch angezeigt.

**Comment by christianbarkowsky** [comment]
Hier funktioniert es in beiden Modis @seibtph
