### ISSUE TITLE
Contao 4.8 error on creating tabs

### ISSUE THREAD

**Issue by GMTeams** [christianbarkowsky/contao-tabcontrol#41]
Contao 4.8

When I try to create a new tab as a contao element, I get the following error message:

> Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /kunden/123/myproject/var/cache/prod/contao/dca/tl_content.php on line 3394

Symfony Cache is cleared. Do you know what I can do? Thanks!

**Comment by christianbarkowsky** [comment]
See issue #42
