### ISSUE TITLE
Contao 3.5 Compatibility

### ISSUE THREAD

**Issue by rustykowski** [christianbarkowsky/contao-tabcontrol#44]
Mit dem aktuellen Release 3.1.12 bekomme ich Probleme unter Contao 3.5. 
Das Release 3.1.10 läuft aber ordentlich.

`Uncaught exception 'Error' with message 'Call to undefined method Contao\StringUtil::deserialize()' thrown in /var/www/www.stevensbikes.com/html/c35/system/modules/tabcontrol/elements/ContentTabControl.php on line 45`

Ich glaube, Contao 3 kennt nur deserialize(), aber nicht \StringUtil::deserialize().

**Comment by christianbarkowsky** [comment]
StringUtil gab es schon unter 3.5

**Comment by christianbarkowsky** [comment]
Hey @rustykowski

ich schließe die Issue. Contao 3.5 ist Geschichte. Aktuell ist die 4.9 LTS!
