### ISSUE TITLE
TabControl funktioniert nicht unter 4.9

### ISSUE THREAD

**Issue by Skipman** [christianbarkowsky/contao-tabcontrol#47]
Hallo Chris,
ich hoffe, Du bist noch aktiv!
Problem: Der Inhalt aller TabSections wird in einem einzigen Feld angezeigt, Die Tabs oberhalb sind nutzlos. Bei Doppelklick auf einen Tab werden gleich alle markiert (die Klasse _selected_ wird nicht mitgegeben).

Contao 4.9.11
CM 1.4.0
PHP 7.4

Der Quellcode ist mit Deinem Beispielcode ident (bis auf die fehlende Klasse selected.

Inhaltselemente:
Reitergruppe Start mit 4 Reiterüberschriften
4 Gruppen mit jeweils mit Panel Anfang - Content - Panel Ende
Am Ende Reitergruppe Ende

Beispiel ist zu sehen unter go21.coboda.at (Entwicklungsdomain)

Kannst Du da mal bitte drüberschauen? Danke im Voraus!

LG Ronald

**Comment by christianbarkowsky** [comment]
Hallo Ronald,

klar bin ich noch aktiv!

Du hast Mootools vergessen im Seitenlayout zu aktivieren.

**Comment by christianbarkowsky** [comment]
Wie ich sehe @Skipman funktioniert es jetzt.

**Comment by Skipman** [comment]
Hallo Christian,

danke für die Info! Die Mootools sind in der Beschreibung nicht erwähnt/abgebildet, dachte daher, das es mit jQuery geht.

Aber jetzt ist alles gut. Danke für den schnellen Support!

LG Ronald

**Comment by christianbarkowsky** [comment]
Das wärde ich noch er­gän­zen.
Es wird eine reine native JS Version geben.

**Comment by Skipman** [comment]
Hallo Christian,

danke für die Info! Die Mootools sind in der Beschreibung nicht erwähnt/abgebildet, dachte daher, dass es mit jQuery geht.

Aber jetzt ist alles gut. Danke für den schnellen Support!

LG Ronald

 

 

Mit freundlichen Grüßen

 

Ronald Boda

 



 

CO/BODA e.U.

Aufeldsiedlung 2/1/6
3143 Pyhra

 

T: +43 (664) 21 85 631

E:  <mailto:info@coboda.at> info@coboda.at

I:  <https://www.coboda.at/> https://www.coboda.at

 

Von: Christian Barkowsky <notifications@github.com> 
Gesendet: Montag, 15. Februar 2021 15:21
An: christianbarkowsky/contao-tabcontrol <contao-tabcontrol@noreply.github.com>
Cc: Ronald Boda <info@coboda.at>; Mention <mention@noreply.github.com>
Betreff: Re: [christianbarkowsky/contao-tabcontrol] TabControl funktioniert nicht unter 4.9 (#47)

 

Closed #47 <https://github.com/christianbarkowsky/contao-tabcontrol/issues/47> .
